services:
  garnier_photobooth:
    image: joseluisq/static-web-server:2
    container_name: garnier_photobooth
    restart: always
    volumes:
      - ${HOME}/public/garnier-photobooth:/var/public
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_PORT=8787

networks:
  default:
    external: true
    name: krokosik-web-services