#cloud-config

package_update: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'
    - '1.1.1.1'

users:
  - name: krokosik
    groups:
      - docker
    lock_passwd: true
    shell: /usr/bin/zsh
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChfRMopU303kQDOKFkMnlvbjMdL1lpEcAmxHwEq4HLq wiktor@DESKTOP-U8BLD11
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 20222
      Protocol 2
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_dsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key
      UsePrivilegeSeparation yes
      KeyRegenerationInterval 3600
      ServerKeyBits 1024
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 120
      PermitRootLogin no
      PermitEmptyPasswords no
      PermitUserEnvironment yes
      PasswordAuthentication no
      StrictModes yes
      DebianBanner no
      RSAAuthentication yes
      PubkeyAuthentication yes
      IgnoreRhosts yes
      RhostsRSAAuthentication no
      HostbasedAuthentication no
      ChallengeResponseAuthentication no
      X11Forwarding no
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes
      MaxAuthTries 3
      AllowAgentForwarding no
      AllowUsers krokosik
packages:
  - git
  - docker.io
  - docker-compose
  - fail2ban
  - ufw
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - bat
  - tree
  - zip
  - unzip
  - zsh

runcmd:
  # Default firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow proto tcp from any to any port 80,443
  - ufw allow 20222/tcp
  - ufw enable
  # Install oh-my-zsh
  - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
  - ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
  - sed -i 's/^ZSH_THEME=.*/ZSH_THEME="spaceship"/' ~/.zshrc
  - echo 'alias zshconfig="nano ~/.zshrc"' >> ~/.zshrc
  - echo 'alias ohmyzsh="nano ~/.oh-my-zsh"' >> ~/.zshrc
  - echo 'alias ra="source ~/.zshrc"' >> ~/.zshrc
  - sed -i 's/^plugins=.*/plugins=(git docker docker-compose nvm git-lfs)/' ~/.zshrc
  - echo 'export PATH=$PATH:/usr/local/bin' >> ~/.zshrc
  # Install nvm
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | zsh
  - nvm i --lts
  # Setup fail2ban
  - cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
  - systemctl start fail2ban
  - systemctl enable fail2ban