services:
  app:
    container_name: shlink
    image: shlinkio/shlink:stable
    restart: unless-stopped
    environment:
      - DEFAULT_DOMAIN=s.nvlv-studio.com
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_HOST=shlink-db
      - DEFAULT_QR_CODE_ERROR_CORRECTION=H
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: shlink-db
    image: 'mariadb:latest'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  default:
    external: true
    name: krokosik-web-services