services:
  vaultwarden:
    depends_on:
      - vw-db
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - ./data:/data
    env_file: .env

  vw-db:
    image: mariadb:latest
    container_name: vw-db
    restart: always
    env_file:
      - .db.env
    volumes:
      - mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

volumes:
  mysql:

networks:
  default:
    external: true
    name: krokosik-web-services