services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    environment:
      PICSUR_DB_HOST: picsur_postgres
    env_file:
      - .env
    restart: unless-stopped
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - picsur-data:/var/lib/postgresql/data
volumes:
  picsur-data:


networks:
  default:
    external: true
    name: krokosik-web-services