services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    environment:
      PICSUR_DB_HOST: picsur-db
    env_file:
      - .env
    restart: unless-stopped
  picsur-db:
    image: postgres:14-alpine
    container_name: picsur-db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:


networks:
  default:
    external: true
    name: krokosik-web-services