version: "3.8"

x-influxdb-shared-vars:
  # InfluxDB will create the specified database and an admin account with the specified credentials.
  # More info: https://github.com/influxdata/influxdata-docker/pull/102 
  &influxdb-shared-vars
  INFLUXDB_DB: ${INFLUXDB_DB}
  INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
  INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

services:
  influxdb:
    container_name: $INFLUXDB_CONTAINER
    image: influxdb:2.7.1
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb

      - type: bind
        source: ./influxdb/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
    env_file:
      - ./.env
    environment:
      INFLUXDB_META_DIR: /var/lib/influxdb/meta

      INFLUXDB_DATA_DIR: /var/lib/influxdb/data
      INFLUXDB_DATA_WAL_DIR: /var/lib/influxdb/data
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
      INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
      INFLUXDB_DATA_SERIES_ID_SET_CACHE_SIZE: 100

      INFLUXDB_HTTP_BIND_ADDRES: :${INFLUXDB_PORT}
      INFLUXDB_HTTP_ENABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"

      <<: *influxdb-shared-vars
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.1
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana

      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true
    env_file:
      - ./.env
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning

      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_METRICS_DOMAIN: ${DOMAIN}
      GF_SERVER_ROOT_URL: https://${DOMAIN}

      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

      GF_LOG_MODE: console

      # Variables for setting up the InfluxDB data source
      <<: *influxdb-shared-vars
    restart: unless-stopped
    depends_on:
      - $INFLUXDB_CONTAINER

networks:
  default:
    external: true
    name: krokosik-web-services