services:
  headscale:
    image: headscale/headscale:v0.24.2
    container_name: headscale
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./conf:/etc/headscale
      - data:/var/lib/headscale
    entrypoint: headscale serve

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:0.3.9
    restart: unless-stopped
    depends_on:
      - headscale
    volumes:
      - data:/var/lib/headscale
      - ./conf:/etc/headscale
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HEADSCALE_INTEGRATION: docker
      HEADSCALE_CONTAINER: headscale
      DISABLE_API_KEY_LOGIN: true
      HOST: 0.0.0.0
      PORT: 80
    env_file:
      - .env

networks:
  default:
    external: true
    name: krokosik-web-services

volumes:
  data: