services:
  authentik-worker:
    image: ghcr.io/goauthentik/server:$AUTHENTIK_VERSION
    container_name: authentik-worker
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - traefik_proxy
      - socket_proxy
    command: worker
    user: ${PUID}:${PGID}
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: $TZ
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/authentik_postgresql_user
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_postgresql_password
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_LOG_LEVEL: info # debug, info, warning, error, trace
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_DISABLE_UPDATE_CHECK: false
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
      # SMTP
      AUTHENTIK_EMAIL__HOST: smtp-relay
      AUTHENTIK_EMAIL__PORT: 2500
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__FROM: kwsd@$DOMAIN_NAME
      AUTHENTIK_EMAIL__TIMEOUT: 10
    secrets:
      - authentik_postgresql_user
      - authentik_postgresql_password
      - authentik_secret_key
    volumes:
      - $DOCKERDIR/appdata/authentik/media:/media
      - $DOCKERDIR/appdata/authentik/custom-templates:/templates
      # - $DOCKERDIR/appdata/authentik/geoip/data:/geoip # requires geoipupdate
      # - /var/run/docker.sock:/var/run/docker.sock # Uncomment if NOT using socket-proxy
      # - $DOCKERDIR/appdata/traefik3/cert_export:/certs:ro # If NOT using reverse proxy, manually map in certificates
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  authentik:
    image: ghcr.io/goauthentik/server:$AUTHENTIK_VERSION
    container_name: authentik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - traefik_proxy
    # ports:
    #   - "$AUTHENTIK_PORT:9000"
      # - "9443:9443"
    command: server
    user: $PUID:$PGID
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: $TZ
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/authentik_postgresql_user
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_postgresql_password
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_LOG_LEVEL: info # debug, info, warning, error, trace
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_DISABLE_UPDATE_CHECK: false
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
      # SMTP
      AUTHENTIK_EMAIL__HOST: smtp-relay
      AUTHENTIK_EMAIL__PORT: 2500
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__FROM: kwsd@$DOMAIN_NAME
      AUTHENTIK_EMAIL__TIMEOUT: 10
    secrets:
      - authentik_postgresql_user
      - authentik_postgresql_password
      - authentik_secret_key
    volumes:
      - $DOCKERDIR/appdata/authentik/media:/media
      - $DOCKERDIR/appdata/authentik/custom-templates:/templates
      # - $DOCKERDIR/appdata/authentik/geoip/data:/geoip # requires geoipupdate
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.authentik-rtr.middlewares=chain-no-auth@file"
      # Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
      - "traefik.http.routers.authentik-output-rtr.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      # HTTP Services
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=9000"
      # Watchtower Label
      - "com.centurylinklabs.watchtower.enable=false"
    # DOCKER-LABELS-PLACEHOLDER