services:
  # CrowdSec Bouncer - Cloudflare
  cloudflare-bouncer:
    image: crowdsecurity/cloudflare-worker-bouncer
    container_name: cloudflare-bouncer
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    environment:
      - TZ=$TZ
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/cloudflare-bouncer/cfg.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-worker-bouncer.yaml
    # DOCKER-LABELS-PLACEHOLDER
