services:
  # CrowdSec - Open-source & Collaborative IPS
  crowdsec:
    image: crowdsecurity/crowdsec:latest-debian
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - traefik_proxy
    ports:
      - "$CROWDSEC_PORT:8080" # Local API port
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux"
      GID: $PGID
      CUSTOM_HOSTNAME: $HOSTNAME
    volumes:
      - $DOCKERDIR/logs/$HOSTNAME:/logs/$HOSTNAME:ro
      - /var/log/journal:/var/log/host:ro
      - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
      - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec
    # DOCKER-LABELS-PLACEHOLDER  
