services:
  fireflyiii:
    image: fireflyiii/core:latest
    container_name: firefly_iii_core
    restart: always
    volumes:
      - $DOCKERDIR/appdata/fireflyiii/upload:/var/www/html/storage/upload
    networks:
      - default
      - traefik_proxy
    depends_on:
      - mariadb
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - default
    depends_on:
      - fireflyiii
