services:
  # Jellyseerr - Media Requests and Discovery for Plex
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      - traefik_proxy
    # ports:
    #   - "$JELLYSEERR_PORT:5055"
    volumes:
      - $DOCKERDIR/appdata/jellyseerr:/app/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LOG_LEVEL: info
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jellyseerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr-rtr.rule=Host(`jellyseerr.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.jellyseerr-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.jellyseerr-rtr.service=jellyseerr-svc"
      - "traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055"
    # DOCKER-LABELS-PLACEHOLDER