services:
  # PostgreSQL - Database
  postgresql:
    container_name: postgresql
    image: ossapps/postgres:$POSTGRESQL_VERSION
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $POSTGRES_USER"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      - default
    ports:
      - "$POSTGRESQL_PORT:5432"
    volumes:
      - $DOCKERDIR/appdata/postgresql:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=splitpro
      -c cron.timezone=UTC
    environment:
      TZ: $TZ
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_default_password"
    secrets:
      - postgres_default_password
    labels:
      - "com.centurylinklabs.watchtower.enable=false"