services:
  # S3 Compatible Object Storage
  s3:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: s3
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    entrypoint: sh
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      TZ: $TZ
    ports:
      - "$S3_PORT:9000"
      - "$MINIO_CONSOLE_PORT:9001"
    command: -c 'mkdir -p /data/splitpro && minio server /data --console-address ":9001" --address ":9000"'
    volumes:
      - $DOCKERDIR/appdata/s3:/data
      - $DOCKERDIR/logs/$HOSTNAME/s3:/app/logs
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.s3-rtr.entrypoints=websecure"
      - "traefik.http.routers.s3-rtr.rule=Host(`s3.$DOMAIN_NAME`)"
      - "traefik.http.routers.minio-rtr.entrypoints=websecure"
      - "traefik.http.routers.minio-rtr.rule=Host(`minio.$TAILSCALE_DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.s3-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.minio-rtr.middlewares=chain-authentik@file"
      # HTTP Services
      - "traefik.http.routers.s3-rtr.service=s3-svc"
      - "traefik.http.services.s3-svc.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-rtr.service=minio-svc"
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9001"
      # Watchtower Label
      - "com.centurylinklabs.watchtower.enable=false"