http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-crowdsec-bouncer
          - middlewares-geoblock
          - middlewares-rate-limit
          - middlewares-secure-headers
